---
services:
  ui:
    build: ui/
    container_name: ui-server
    ports:
      - 443:443
    healthcheck:
      test: ["CMD", "curl", "--fail", "--ca-cert", "/etc/nginx/ssl/cert.pem", "https://localhost", "||", "exit", "1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:
    build: server/
    container_name: server
    environment:
      TLSEnabled: true
      TLSCertPath: /bin/cert.pem
      TLSKeyPath: /bin/key.pem
      ServerPort: 8443
    ports:
      - 8443:8443
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://localhost:8080/healthz", "||", "exit", "1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s
    # depends_on:
      # - database

  database:
    image: postgres:16
    container_name: server-db
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "server"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s  

volumes:
  dbdata:
    name: db_volume