# Build React app

# Copy manifest.json into Python image
# Run Python script to generate NGINX configuration directives from manifest
# Also generate SSL certs here since we will discard this image

# Create NGINX container, copy config, generated directives, content from React build