import json

# Load the manifest file generated by Vite
with open('manifest.json') as f:
    manifest = json.load(f)

# Generate http2_push directives
directives = []

for css in manifest["index.html"]["css"]:
    file_path = f"/{css}"
    directives.append(f"    http2_push {file_path};")

for file_info in manifest.values():
    file_path = f"/{file_info['file']}"
    directives.append(f"    http2_push {file_path};")

# Write to a file for inclusion in the NGINX config
with open('push_directives.conf', 'w') as f:
    f.write("\n".join(directives))
